Implementation tweaks
* Documentation
* Remove the two levels of indirection in config deployment
* Wait for "save ns config" to succeed
* Simplify Dockerfile, create everything in a single RUN step
* Reduce the wait time -- repeat "add system user" until it works

diff --git a/netsim/ansible/tasks/deploy-config/netscaler.yml b/netsim/ansible/tasks/deploy-config/netscaler.yml
--- a/netsim/ansible/tasks/deploy-config/netscaler.yml
+++ b/netsim/ansible/tasks/deploy-config/netscaler.yml
@@ -3,16 +3,17 @@
 
 - name: "Netscaler: deploying {{ netsim_action }} from {{ config_template }}"
   ansible.builtin.raw: |
-    cat > /tmp/deploy.sh << 'NETSCALER_EOF'
-    #!/bin/bash
+    AUTHENTICATE=127.0.0.1:{{ ansible_user }}:{{ ansible_ssh_pass }}
     while IFS= read -r line; do
-      [ -n "$line" ] && nscli -U 127.0.0.1:{{ ansible_user }}:{{ ansible_ssh_pass }} "$line" || true
+      [ -n "$line" ] && nscli -U "$AUTHENTICATE" "$line" || true
     done << 'CONFIG_EOF'
     {{ deployed_config }}
     CONFIG_EOF
-    nscli -U 127.0.0.1:{{ ansible_user }}:{{ ansible_ssh_pass }} "save ns config"
-    NETSCALER_EOF
-    chmod +x /tmp/deploy.sh
-    sh /tmp/deploy.sh
+
+    if ! nscli -U "$AUTHENTICATE" "save ns config"; then
+      echo "Save failed waiting..."
+      sleep 5
+      nscli -U "$AUTHENTICATE" "save ns config"
+    fi
   when: not ansible_check_mode
   tags: [ print_action, always ]
