Critical bug fix: Cumulus Linux VM does not recognize all files in /etc/network/interface.d
The '/etc/network/interfaces' configuration in CL containers includes all files in
'/etc/network/interface.d' directory, while the corresponding configuration in CL VM
includes only the files with '.intf' suffix. Configuration templates introduced in
release 1.3.1 result in empty configuration on Cumulus Linux VM.

This fix adds '.intf' suffix to all 'ifupdown' Cumulus Linux configuration files.

diff --git a/netsim/ansible/templates/vlan/cumulus.j2 b/netsim/ansible/templates/vlan/cumulus.j2
--- a/netsim/ansible/templates/vlan/cumulus.j2
+++ b/netsim/ansible/templates/vlan/cumulus.j2
@@ -1,3 +1,7 @@
+#!/bin/bash
+#
+set -e # Exit immediately when any command fails
+#
 {% macro ipaddr(ifdata,loopback) -%}
 {%   if ifdata.ipv4 is defined %}
     address {{ ifdata.ipv4 if ifdata.ipv4 is string else loopback.ipv4 }}
@@ -6,13 +10,10 @@
     address {{ ifdata.ipv6 }}
 {%   endif %}
 {%- endmacro %}
-#!/bin/bash
-#
-set -e # Exit immediately when any command fails
 #
 # Create multi-vlan bridge, specify VLANs, and attach interfaces to it
 #
-cat >/etc/network/interfaces.d/50-bridge <<CONFIG
+cat >/etc/network/interfaces.d/50-bridge.intf <<CONFIG
 auto bridge
 allow-vlanbridge bridge
 iface bridge
@@ -29,7 +30,7 @@ CONFIG
 #
 # Create VLAN interfaces
 #
-cat >/etc/network/interfaces.d/51-bridge-interfaces <<CONFIG
+cat >/etc/network/interfaces.d/51-bridge-interfaces.intf <<CONFIG
 {% for ifdata in interfaces if ifdata.vlan is defined %}
 allow-vlanintf {{ ifdata.ifname }}
 iface {{ ifdata.ifname }}
