Fix logic to detect not-failed tests expected to fail

diff --git a/tests/platform-integration/validate/00-expect-logic.yml b/tests/platform-integration/validate/00-expect-logic.yml
--- a/tests/platform-integration/validate/00-expect-logic.yml
+++ b/tests/platform-integration/validate/00-expect-logic.yml
@@ -27,33 +27,30 @@ validate:
     nodes: [ dut_frr ]
     plugin: ping('172.42.42.42')
     _expect_fail: True
+  ping_XP_NF:
+    nodes: [ dut_frr ]
+    plugin: ping('h1')
+    _expect_fail: True
 
 files:
   validate_logic.sh: |
-    if ! netlab validate ping_OK -q; then           # OK should succeed
-      echo "OK test failed"
-      exit 1
-    fi
-    echo "OK test completed"
-    echo ""
-    #
-    if ! netlab validate ping_EXPECT -q; then       # EXPECT (to fail) should also succeed
-      echo "EXPECT-to-fail test did not succeed"
-      exit 1
-    fi
-    echo "EXPECT-to-fail test completed"
-    echo ""
-    if netlab validate ping_FAIL; then              # FAIL should FAIL
-      echo "A test that should fail did not"
-      exit 1
-    fi
-    echo "FAIL test failed as expected"
-    echo ""
-    netlab validate ping_WARN
-    WARN_EXIT=$?
-    if [ $WARN_EXIT -ne 3 ]; then                   # WARN should fail with error code 3
-      echo "A test that should generate a warning did not return exit code 3 (got $WARN_EXIT)"
-      exit 1
-    fi
-    echo "WARN test behaved as expected"
-    echo ""
+    check_validate() {
+      netlab validate -q $1                         # execute a test
+      EXIT_CODE=$?
+      if [ $EXIT_CODE -ne $2 ]; then                # did we get the expected exit code?
+        echo "===================================================================="
+        echo "FAIL: $1 scenario returned exit code $EXIT_CODE (expected $2)"
+        echo "===================================================================="
+        exit 1
+      fi
+      echo "===================================================================="
+      echo "SUCCESS: $1 passed with exit code $2"
+      echo "===================================================================="
+      echo
+    }
+
+    check_validate ping_OK 0
+    check_validate ping_EXPECT 0
+    check_validate ping_FAIL 1
+    check_validate ping_WARN 3
+    check_validate ping_XP_NF 1
